name: lf
channels:
  - conda-forge
dependencies:
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - xtl
  - nlohmann_json>=3.11.2
  - cppzmq
  - jupyter_kernel_test
  - xonsh
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
  - zlib
