name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11
  - toml
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - re2c
  - numpy
  - python
  - bison=3.4
  - cmake
  - make
